### ISSUE TITLE
[bug] app 레슨 삭제시 리렌더 안되는 현상

### ISSUE THREAD

**Issue by leekh716** [innovationacademy-kr/slabs-munetic#114]
## 기능 내용
/lesson/manage 페이지에서 레슨 삭제시 삭제는 되지만 state변화가 없어서 리렌더가 되지 않아 새로고침을 해야 삭제된 레슨이 안보이게 됨.
새로고침하지 않아도 삭제되도록 변경해야함

**Comment by evelon** [comment]
feat보다는 bug가 맞지 않을까요?
