### ISSUE TITLE
[bug] ec2 배포 후 관리자 사이트에서 Login api가 작동하지 않는 문제

### ISSUE THREAD

**Issue by chaeinP** [innovationacademy-kr/slabs-munetic#124]
둘 중 하나를 참고하여 작성할 것. bug, feat 외에 commit 타입을 선택해서 작성 가능합니다.

### 발견 일시
2022.01.06 03:30pm

### 증상
로컬 환경에서 작동하던 api가 작동하지 않습니다
refreshToken을 확인하는 api는 작동하는데 login api가 502 bad gateway 응답을 보내 로그인이 불가능한 상황입니다.

admin onwer 계정
아이디 : munetic@gmail.com
비밀번호: 1234

### 스크린샷
<img width="1438" alt="스크린샷 2022-01-06 오후 3 15 34" src="https://user-images.githubusercontent.com/50102773/148339246-2c58ca9d-896c-4c39-8359-fd8c768b782f.png">

**Comment by evelon** [comment]
express와 db가 연결되지 않는 문제를 발견했고 이 문제의 원인임을 확인했습니다.
