### ISSUE TITLE
✨  certificate domain for production profile

### ISSUE THREAD

**Issue by kenu** [innovationacademy-kr/slabs-munetic#130]
## [feat] dev 만 적용한 것 같은데, prod 도메인도 필요합니다.
<img width="484" alt="스크린샷 2022-01-07 오후 3 44 09" src="https://user-images.githubusercontent.com/718691/148509679-66858959-8cb8-4fa0-a381-034788860f3c.png">
* https://munetic.dev.42cadet.kr 는 이상없는데,
* https://munetic.42cadet.kr 도메인에 걸린 인증서는 dev 것입니다.

## 기능 내용
munetic.42cadet.kr Letsencrypt SSL 설정

**Comment by evelon** [comment]
![image](https://user-images.githubusercontent.com/3518710/148646257-759ebbb8-7441-4f18-8abd-ccf2239291e7.png)
main 브랜치에 올려서 munetic.42cadet.kr에도 배포를 하였습니다.!
