### ISSUE TITLE
[bug] 배포 사이트 새로고침 또는 경로 직접 입력할때 404notfound가 뜨는 에러

### ISSUE THREAD

**Issue by chaeinP** [innovationacademy-kr/slabs-munetic#146]
### 발견 일시
2022.01.10 새벽

### 증상
app과 admin홈화면은 정상작동하지만 그 외 경로에서 새로고침을하거나 url로 직접 입력해서 이동하면 404페이지가 뜸

### 발생 위치 (optional)
배포 사이트 app, admin 모두에서 발생

### 스크린샷
![스크린샷 2022-01-10 오전 12 36 24](https://user-images.githubusercontent.com/50102773/148713414-88ee9ebd-e586-4d3c-b843-3d8760ccf898.png)

**Comment by evelon** [comment]
serve의 모드 문제였습니다. -s (--single) 옵션을 추가하여 해결을 시도중입니다.
참고 (https://github.com/zuiidea/antd-admin/issues/847)
