### ISSUE TITLE
[feat] 리플 기능 구현 - 댓글 작성

### ISSUE THREAD

**Issue by seohee-choi** [innovationacademy-kr/slabs-munetic#174]
### 프론트엔드

- [x] 댓글 작성 페이지 목업 구현
- [x] 별점 입력
- [x] 댓글 입력
- [x] 별점 및 댓글 내용 유효성 검사
- [x] 댓글 내용 서버로 전송

### 백엔드

- [x] 댓글 내용 저장 (댓글 ID, 게시글 ID, 사용자 ID, 댓글내용, 별점)

**Comment by joohongpark** [comment]
로컬상에서 기능구현 완료되었으며 #178 이 merge 되면 이어서 커밋할 예정.
