### ISSUE TITLE
[bug] aws 용량부족 및 자동배포 불가

### ISSUE THREAD

**Issue by Jay13Jeong** [innovationacademy-kr/slabs-munetic#253]
### 발견 일시
2022.05.26
### 증상
깃액션에서 자동 배포시 no space 에러가 발생
### 발생 위치 (optional)
https://github.com/innovationacademy-kr/slabs-munetic/runs/6606499705?check_suite_focus=true
"executing remote ssh commands using key"부분의 162번줄
### 발생 커밋
https://github.com/innovationacademy-kr/slabs-munetic/actions/runs/2389541553
### 재현 방법
develop브랜치에 push시 액션에서 aws에 자동배포중 발생
### 스크린샷
<img width="575" alt="스크린샷 2022-05-26 오후 6 02 08" src="https://user-images.githubusercontent.com/63899204/170455785-6488c22b-cb39-4e7f-89f4-86e530af38fb.png">

---

**Comment by kenu** [comment]
```
[ec2-user@ip-172-26-4-57 ~]$ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        2.0G     0  2.0G   0% /dev
tmpfs           2.0G     0  2.0G   0% /dev/shm
tmpfs           2.0G  796K  2.0G   1% /run
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/xvda1       80G   80G  1.2M 100% /
tmpfs           395M     0  395M   0% /run/user/1000
```

`/var/lib/docker/overlay2` 오래된 폴더 삭제해야 할 것 같아 보입니다.
```
[ec2-user@ip-172-26-4-57 ~]$ docker system df
TYPE            TOTAL     ACTIVE    SIZE      RECLAIMABLE
Images          144       6         32.77GB   32.01GB (97%)
Containers      186       5         17.97GB   17.97GB (99%)
Local Volumes   18        0         0B        0B
Build Cache     0         0         0B        0B
```
## related
* https://stackoverflow.com/questions/46672001/is-it-safe-to-clean-docker-overlay2
* https://unix.stackexchange.com/questions/130786/can-i-remove-files-in-var-log-journal-and-var-cache-abrt-di-usr

**Comment by Jay13Jeong** [comment]
<img width="412" alt="캡처" src="https://user-images.githubusercontent.com/63899204/170635592-89e38334-8883-4e01-8fee-f51f55ac5807.PNG">
알려주신 폴더로 접근 할 수가 없습니다. sudo cd명령으로도 접근 불가능합니다.

**Comment by kenu** [comment]
<img width="402" alt="스크린샷 2022-05-27 오후 2 39 40" src="https://user-images.githubusercontent.com/718691/170637064-55324926-c651-4232-895e-fc306b521180.png">
참참고하세요. :)

**Comment by Jay13Jeong** [comment]
어드바이스감사합니다. 해결했습니다 :)
