### ISSUE TITLE
[test] service 단위 테스트 짜기

### ISSUE THREAD

**Issue by evelon** [innovationacademy-kr/slabs-munetic#72]
- [x] createLesson
- [x] findLesson
- [x] editLesson
- [x] removeLesson

**Comment by evelon** [comment]
해당 테스트들은 모두 데이터베이스를 seed로 초기화한 상태에서만 동작합니다.

**Comment by evelon** [comment]
#74 의 문제가 있습니다.

**Comment by evelon** [comment]
문제가 생겨 모두 제거하였습니다.

**Comment by kenu** [comment]
고생 많아요. CRUD 테스트의 경우 H2, SQLite 같은 테스트용 DB를 따로 만들어서 돌리는 경우가 많습니다. 실제 운용되는 DB를 연결해서 테스트 케이스를 돌리면 위험하기 때문이죠.

**Comment by evelon** [comment]
jest를 포기했습니다! 현재 돌리는 DB에 아무 데이터가 없기 때문에 테스트용 DB로 사용하고는 있긴 한데... 나중에 sqlite로 따로 연결하여 seed를 구성하면 될 것 같습니다.

**Comment by kenu** [comment]
일단 돌아가는 코드에 더 포커스를 맞추기를 바랍니다. 응원합니다.
