### ISSUE TITLE
[bug] jest가 'Cannot log after tests are done.'를 내보내는 문제.

### ISSUE THREAD

**Issue by evelon** [innovationacademy-kr/slabs-munetic#74]
### 발견 일시
21.12.23 목 11:32

### 증상
테스트가 잘 되다가 갑자기 스크린샷과 같은 문제가 납니다. 더불어 jest가 종료되지 않아 강제종료해야합니다.

### 발생 위치 (optional)
munetic_express/src/test/service/lesson.test.ts (or lesson.service.test.ts)

### 발생 커밋
83cafd3827c6aad0ddcaecca584996d92986a80f

### 재현 방법
알 수 없음 
![image](https://user-images.githubusercontent.com/3518710/147179037-e6e6fe4c-4ec8-4ea2-a012-59d5d9193fd1.png)

### 스크린샷
<img width="762" alt="image" src="https://user-images.githubusercontent.com/3518710/147178993-e647a5cb-8f8c-4e10-be24-4e1946b363ea.png">

**Comment by evelon** [comment]
포기

**Comment by chaeinP** [comment]
저도 같은 에러를 만났는데 테스트 가장 앞단에 before구문으로 db를 sync해주면 해결되는 것 같았어요
